name: Build and verify microcks
description: |
  Build and verify microcks into a single action
  Pre-requisites:
  * Checkout on microcks/microcks
outputs:
  build-timestamp:
    description: build timestamp
    value: ${{ steps.build-timestamp.outputs.date }}
runs:
  using: composite
  steps:
    - name: Get current date
      shell: bash
      id: build-timestamp
      run: |
        echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
        echo "testing CI"

    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
        architecture: x64
        cache: maven

    - name: Build Java components
      shell: bash
      run: mvn -B clean install

    - name: Build Angular app
      shell: bash
      run: cd ${{github.workspace}}/webapp && mvn -B -Pprod -DskipTests package

    - name: Run Integration tests
      shell: bash
      run: |
        cd ${{github.workspace}}/webapp && mvn -Pit test
        cd ${{github.workspace}}/minions/async && mvn -Pit test

    - name: Verify Javadoc completion
      shell: bash
      run: mvn -B javadoc:javadoc
