name: Package microcks
description: |
  Package microcks into a single action.
  Pre-requisites:
  * Checkout on microcks/microcks
  * Ensure the java and maven are setup.
inputs:
  image-tag:
    description: image tag
    required: true
  build-timestamp:
    description: build timestamp
    required: true
  dockerhub-username:
    description: docker username
    required: true
  dockerhub-token:
    description: docker token
    required: true
  quay-username:
    description: quay username
    required: true
  quay-token:
    description: quay token
    required: true
runs:
  using: composite
  steps:
    - name: Set up JDK 21 for x64
      uses: actions/setup-java@v4
      with:
        java-version: "21"
        distribution: "temurin"
        architecture: x64
        cache: maven

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub-username }}
        password: ${{ inputs.dockerhub-token }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.quay-username }}
        password: ${{ inputs.quay-token }}

    - name: Login to Quay.io and Docker Hub registries and setup multi-arch builder
      shell: bash
      env:
        BUILDER: buildx-multi-arch
      run:
        docker buildx inspect $BUILDER || docker buildx create --name=$BUILDER
        --driver=docker-container --driver-opt=network=host

    - name: Package webapp in prod mode
      shell: bash
      run: |
        cd ${{github.workspace}}/webapp
        # We should install the webapp to have the JAR with UI, available for the Uber distro
        mvn -B -q -Pprod -DskipTests install

    - name: Build and push container image for webapp
      id: build-and-push-webapp
      uses: docker/build-push-action@v6.10.0
      with:
        context: ${{github.workspace}}/webapp
        sbom: true
        push: true
        provenance: mode=max
        platforms: linux/amd64,linux/arm64
        builder: buildx-multi-arch
        file: webapp/src/main/docker/Dockerfile
        labels: |
          org.opencontainers.image.revision=${GITHUB_SHA}
          org.opencontainers.image.created=${{ inputs.build-timestamp }}
        tags: quay.io/microcks/microcks:${{inputs.image-tag}},docker.io/microcks/microcks:${{inputs.image-tag}}

    - name: Sign the webapp images with GitHub OIDC Token
      shell: bash
      env:
        DIGEST: ${{ steps.build-and-push-webapp.outputs.digest }}
        TAGS: quay.io/microcks/microcks:${{inputs.image-tag}}
          docker.io/microcks/microcks:${{inputs.image-tag}}
        COSIGN_EXPERIMENTAL: "true"
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}

    - name: Package async minion in prod mode
      shell: bash
      run: |
        cd ${{github.workspace}}/minions/async
        mvn -B -q -DskipTests -Dquarkus.package.type=legacy-jar package

    - name: Build and push container for async minion
      id: build-and-push-async
      uses: docker/build-push-action@v6.10.0
      with:
        context: ${{github.workspace}}/minions/async
        sbom: true
        push: true
        provenance: mode=max
        platforms: linux/amd64,linux/arm64
        builder: buildx-multi-arch
        file: minions/async/src/main/docker/Dockerfile.legacy-jar
        labels: |
          org.opencontainers.image.revision=${GITHUB_SHA}
          org.opencontainers.image.created=${{ inputs.build-timestamp }}
        tags: quay.io/microcks/microcks-async-minion:${{inputs.image-tag}},docker.io/microcks/microcks-async-minion:${{inputs.image-tag}}

    - name: Sign the async minion images with GitHub OIDC Token
      shell: bash
      env:
        DIGEST: ${{ steps.build-and-push-async.outputs.digest }}
        TAGS: quay.io/microcks/microcks-async-minion:${{inputs.image-tag}}
          docker.io/microcks/microcks-async-minion:${{inputs.image-tag}}
        COSIGN_EXPERIMENTAL: "true"
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}

    - name: Package uber distro in prod mode
      shell: bash
      run: |
        cd ${{github.workspace}}/distro/uber
        mvn -B -q -Pprod -DskipTests package

    - name: Build and push container image for uber distro
      id: build-and-push-uber
      uses: docker/build-push-action@v6.10.0
      with:
        context: ${{github.workspace}}/distro/uber
        sbom: true
        push: true
        provenance: mode=max
        platforms: linux/amd64,linux/arm64
        builder: buildx-multi-arch
        file: distro/uber/src/main/docker/Dockerfile
        labels: |
          org.opencontainers.image.revision=${GITHUB_SHA}
          org.opencontainers.image.created=${{ inputs.build-timestamp }}
        tags: quay.io/microcks/microcks-uber:${{inputs.image-tag}},docker.io/microcks/microcks-uber:${{inputs.image-tag}}

    - name: Sign the uber distro images with GitHub OIDC Token
      shell: bash
      env:
        DIGEST: ${{ steps.build-and-push-uber.outputs.digest }}
        TAGS: quay.io/microcks/microcks-uber:${{inputs.image-tag}}
          docker.io/microcks/microcks-uber:${{inputs.image-tag}}
        COSIGN_EXPERIMENTAL: "true"
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}

    - name: Package async minion in uber distro in prod mode
      shell: bash
      run: |
        cd ${{github.workspace}}/distro/uber-async-minion
        mvn -B -q -DskipTests package

    - name: Build and push container for async minion in uber distro
      id: build-and-push-uber-async
      uses: docker/build-push-action@v6.10.0
      with:
        context: ${{github.workspace}}/distro/uber-async-minion
        sbom: true
        push: true
        provenance: mode=max
        platforms: linux/amd64,linux/arm64
        builder: buildx-multi-arch
        file: distro/uber-async-minion/src/main/docker/Dockerfile.jvm
        labels: |
          org.opencontainers.image.revision=${GITHUB_SHA}
          org.opencontainers.image.created=${{ inputs.build-timestamp }}
        tags: quay.io/microcks/microcks-uber-async-minion:${{inputs.image-tag}},docker.io/microcks/microcks-uber-async-minion:${{inputs.image-tag}}

    - name: Sign the async minion in uber distro images with GitHub OIDC Token
      shell: bash
      env:
        DIGEST: ${{ steps.build-and-push-uber-async.outputs.digest }}
        TAGS: quay.io/microcks/microcks-uber-async-minion:${{inputs.image-tag}}
          docker.io/microcks/microcks-uber-async-minion:${{inputs.image-tag}}
        COSIGN_EXPERIMENTAL: "true"
      run: |
        images=""
        for tag in ${TAGS}; do
          images+="${tag}@${DIGEST} "
        done
        cosign sign --yes ${images}