name: build-verify
on:
  push:
    paths-ignore:
      #- '.github/**'
      - ".gitignore"
      - "LICENSE"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".github/**"
      - ".gitignore"
      - "LICENSE"
      - "*.md"
permissions: read-all
jobs:
  build-verify:
    runs-on: ubuntu-latest
    environment: build-${{ github.ref_name }}
    permissions:
      contents: read
      id-token: write # needed for signing the images with GitHub OIDC Token
    # outputs:
    #   build-timestamp: ${{ steps.run-build.outputs.build-timestamp}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Build and verify
      #   id: run-build
      #   uses: ./.github/actions/build-test
